---

- name: Create airflow user
  user:
    name: "{{ airflow_user }}"
    createhome: false
    system: true
  tags: 
    - airflow_setup

- name: Create airflow directory structure
  file:
    path: "{{ airflow_install_directory }}"
    state: directory
    recurse: true
    mode: 0755
    owner: "{{ airflow_user }}"
    group: "{{ airflow_group }}"
  tags: 
    - airflow_setup

- name: Template out airflow configuration
  template:
    src: usr/share/airflow/airflow.cfg.j2
    dest: "{{ airflow_install_directory }}/airflow.cfg"
    mode: 0644
    owner: "{{ airflow_user }}"
    group: "{{ airflow_group }}"
  tags: 
    - airflow_configure

- name: Symlink /usr/bin/airflow to /usr/local/bin/airflow
  file:
    state: link
    src: /usr/bin/airflow
    dest: /usr/local/bin/airflow
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
  tags: 
    - airflow_configure

- name: Install systemd services
  template:
    src: etc/systemd/system/airflow-{{item}}.service.j2
    dest: /etc/systemd/system/airflow-{{item}}.service
  with_items: "{{ airflow_services }}"
  when: use_systemd is defined and use_systemd
  notify:
    - enable services
    - restart services
  tags: 
    - airflow_setup

- name: Install supervisord services
  include: install-supervisor.yml
  when: use_supervisor is defined and use_supervisor
  tags: 
    - airflow_setup