---

- name: Install Supervisor
  apt: name=supervisor state=installed
  tags:
    - supervisor

- name: Ensure supervisor service is started
  service: name=supervisor state=started enabled=yes
  tags:
    - supervisor

- name: Create supervisor group
  group:
    name: supervisor
    state: present

- name: Add users to supervisor group
  user:
    name: "{{ item }}"
    groups: supervisor
    append: yes
  with_items:
    - "{{ airflow_user }}"
    - root

- name: remove line current chmod line from supervisor global config
  lineinfile: dest=/etc/supervisor/supervisord.conf
              state=absent
              regexp='^chmod=0700'
  notify: restart supervisord

- name: add lines to supervisor global config to set permissions on socket
  blockinfile:
    dest: /etc/supervisor/supervisord.conf
    insertafter: "file=/var/run/supervisor\\.sock.*"
    block: |
      chmod=0770 ; socket file mode (default 0700)
      chown=root:supervisor
    marker: "; {mark} ANSIBLE MANAGED BLOCK"
  notify: restart supervisord

- name: Copy over supervisor config template for each airflow service
  template:
    src: etc/supervisor/conf.d/airflow-generic.conf.j2
    dest: /etc/supervisor/conf.d/airflow-{{item}}.conf
  with_items: "{{ airflow_services }}"
  vars:
    service: "{{ item }}"
  notify: restart supervisord

- name: Copy over supervisor startup script template for each airflow service
  template:
    src: "{{ supervisor_start_template }}"
    dest: "{{ airflow_install_directory }}/{{ item }}_start.sh"
    owner: "{{ airflow_user }}"
    group: "{{ airflow_user }}"
    mode: 0755
  vars: 
    service: "{{ item }}"
  with_items: "{{ airflow_services }}"
  notify: restart supervisord

- name: Re-read the Supervisor config files
  command: supervisorctl reread
  tags:
    - celery

- name: Update Supervisor to add the app in the process group
  command: supervisorctl update
  tags:
    - celery