---

- name: Install dependency packages
  yum:
    name: "{{ item }}"
  with_items:
    - gcc
    - python-setuptools
    - python-devel

- name: Install pip
  easy_install:
    name: pip

- name: Symlink /usr/bin/airflow to /usr/local/bin/airflow
  file:
    state: link
    src: /usr/bin/airflow
    dest: /usr/local/bin/airflow
