---

- name: Install dependency packages
  yum:
    name: "{{ item }}"
  with_items:
    - gcc
    - python-setuptools
    - python-devel
  tags: airflow_install

- name: Install pip
  easy_install:
    name: pip
  tags: airflow_install

